Revert r22747: regression under Python 2.3
TestOurServerOurClient.test_openFileExtendedAttributes timeouts under Python
2.3, with failure:
exceptions.AssertionError: still have data in OPEN: '\x00\x00\x00\x01\x00\x00\x00\x03foo\x00\x00\x00\x03bar'

Reopens #3010